export const SAVE_PERSON = 'SAVE_PERSON';
export const LOAD_STARTED_PERSON = 'LOAD_STARTED_PERSON';
export const SET_SELECTED_PERSON = 'SET_SELECTED_PERSON';
export const LOAD_PERSON_FAILED = 'LOAD_PERSON_FAILED';
