export const SAVE_PLANET = 'SAVE_PLANET';
export const LOAD_STARTED_PLANET = 'LOAD_STARTED_PLANET';
export const SET_SELECTED_PLANET = 'SET_SELECTED_PLANET';
export const LOAD_PLANET_FAILED = 'LOAD_PLANET_FAILED';
