export const SAVE_SPECIES = 'SAVE_SPECIES';
export const LOAD_STARTED_SPECIES = 'LOAD_STARTED_SPECIES';
export const SET_SELECTED_SPECIES = 'SET_SELECTED_SPECIES';
export const LOAD_SPECIES_FAILED = 'LOAD_SPECIES_FAILED';
export const TOGGLE_SPECIES_VISIBLE = 'TOGGLE_SPECIES_VISIBLE';
export const REVERT_LOAD_SPECIES = 'REVERT_LOAD_SPECIES';
