export const SAVE_STARSHIP = 'SAVE_STARSHIP';
export const LOAD_STARTED_STARSHIP = 'LOAD_STARTED_STARSHIP';
export const SET_SELECTED_STARSHIP = 'SET_SELECTED_STARSHIP';
export const LOAD_STARSHIP_FAILED = 'LOAD_STARSHIP_FAILED';
export const TOGGLE_STARSHIP_VISIBLE = 'TOGGLE_STARSHIP_VISIBLE';
export const REVERT_LOAD_STARSHIPS = 'REVERT_LOAD_STARSHIPS';
