export const SAVE_VEHICLE = 'SAVE_VEHICLE';
export const LOAD_STARTED_VEHICLE = 'LOAD_STARTED_VEHICLE';
export const SET_SELECTED_VEHICLE = 'SET_SELECTED_VEHICLE';
export const LOAD_VEHICLE_FAILED = 'LOAD_VEHICLE_FAILED';
export const TOGGLE_VEHICLE_VISIBLE = 'TOGGLE_VEHICLE_VISIBLE';
export const REVERT_LOAD_VEHICLES = 'REVERT_LOAD_VEHICLES';
