export const SAVE_PERSON = 'SAVE_PERSON';
export const LOAD_STARTED_PERSON = 'LOAD_STARTED_PERSON';
export const SET_SELECTED_PERSON = 'SET_SELECTED_PERSON';
export const LOAD_PERSON_FAILED = 'LOAD_PERSON_FAILED';
export const TOGGLE_PERSON_VISIBLE = 'TOGGLE_PERSON_VISIBLE';
export const REVERT_LOAD_PERSON = 'REVERT_LOAD_PERSON';
